services:
  mapapp:
    image: someone15me/voice-gis-app:latest
    container_name: voice_gis_app
    ports:
      - "5000:5000"
    volumes:
      - ./MapApp/uploads:/app/uploads
    restart: unless-stopped
