services:
  mapapp:
    build:
      context: ./MapApp
    container_name: voice_gis_app
    ports:
      - "5000:5000"
    volumes:
      - ./MapApp/uploads:/app/uploads
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
