apiVersion: v1
kind: Service
metadata:
  name: voice-gis-app
  labels:
    app: voice-gis-app
spec:
  type: ClusterIP
  selector:
    app: voice-gis-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
