apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-gis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voice-gis-app
  template:
    metadata:
      labels:
        app: voice-gis-app
    spec:
      containers:
      - name: voice-gis-app
        image: someone15me/voice-gis-app:latest
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
