apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voice-gis-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: ""  # Empty means catch all requests
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voice-gis-app
                port:
                  number: 80
