apiVersion: v1
kind: Service
metadata:
  name: voice-gis-app
spec:
  type: ClusterIP
  selector:
    app: voice-gis-app
  ports:
    - port: 80          # Exposed as port 80 internally
      targetPort: 5000  # Maps to container port
